---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Static Analysis
        run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
